// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CartSchemaCart struct {
	CartID    int32            `json:"cartID"`
	Owner     string           `json:"owner"`
	Name      string           `json:"name"`
	CartName  string           `json:"cartName"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type CartSchemaCartItems struct {
	CartItemID int32            `json:"cartItemID"`
	CartID     int32            `json:"cartID"`
	ProductID  int32            `json:"productID"`
	Quantity   int32            `json:"quantity"`
	Ischecked  bool             `json:"ischecked"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}
