// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"context"
)

type Querier interface {
	// 获取用户的购物车ID
	//
	//
	//  UPDATE cart_schema.cart_items AS ci
	//  SET ischecked = TRUE
	//  WHERE ci.cart_id =
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3 LIMIT 1)
	//      AND ci.product_id = $4
	CheckCartItem(ctx context.Context, arg CheckCartItemParams) error
	//CreateCart
	//
	//  INSERT INTO cart_schema.cart (owner, name, cart_name)
	//  VALUES ($1, $2, $3)
	//  RETURNING cart_id, owner, name, cart_name, status, created_at, updated_at
	CreateCart(ctx context.Context, arg CreateCartParams) (CartSchemaCart, error)
	//CreateOrder
	//
	//  SELECT ci.product_id, ci.quantity
	//  FROM cart_schema.cart_items AS ci
	//  WHERE ci.cart_id =
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3 LIMIT 1)
	//      AND ci.ischecked = TRUE
	CreateOrder(ctx context.Context, arg CreateOrderParams) ([]CreateOrderRow, error)
	//EmptyCart
	//
	//  DELETE FROM cart_schema.cart_items AS ci
	//  WHERE ci.cart_id =
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3)
	EmptyCart(ctx context.Context, arg EmptyCartParams) error
	//GetCart
	//
	//  SELECT ci.product_id, ci.quantity
	//  FROM cart_schema.cart_items AS ci
	//  WHERE ci.cart_id =
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3 LIMIT 1)
	GetCart(ctx context.Context, arg GetCartParams) ([]GetCartRow, error)
	//ListCarts
	//
	//  SELECT c.cart_id,c.cart_name
	//  FROM cart_schema.cart AS c
	//  WHERE c.owner = $1 AND c.name = $2
	ListCarts(ctx context.Context, arg ListCartsParams) ([]ListCartsRow, error)
	// 获取用户的购物车ID
	//
	//
	//
	//  DELETE FROM cart_schema.cart_items AS ci
	//  WHERE ci.cart_id =
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3 LIMIT 1)  -- 获取用户的购物车ID
	//      AND ci.product_id = $4  -- 删除指定商品ID
	//  RETURNING cart_item_id, cart_id, product_id, quantity, ischecked, created_at, updated_at
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) (CartSchemaCartItems, error)
	//UncheckCartItem
	//
	//  UPDATE cart_schema.cart_items AS ci
	//  SET ischecked = FALSE
	//  WHERE ci.cart_id =
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3 LIMIT 1)
	//      AND ci.product_id = $4
	UncheckCartItem(ctx context.Context, arg UncheckCartItemParams) error
	//UpsertItem
	//
	//  INSERT INTO cart_schema.cart_items (cart_id, product_id, quantity, created_at, updated_at)
	//  VALUES (
	//      (SELECT c.cart_id
	//       FROM cart_schema.cart AS c
	//       WHERE c.owner = $1 AND c.name = $2 AND c.cart_name = $3 LIMIT 1),  -- 获取用户的购物车ID
	//      $4,   -- 商品ID
	//      $5,   -- 商品数量
	//      CURRENT_TIMESTAMP,  -- 创建时间
	//      CURRENT_TIMESTAMP   -- 更新时间
	//  )
	//  ON CONFLICT (cart_id, product_id)  -- 如果购物车ID和商品ID组合重复
	//  DO UPDATE SET
	//      quantity = cart_schema.cart_items.quantity + EXCLUDED.quantity,  -- 更新商品数量
	//      updated_at = CURRENT_TIMESTAMP  -- 更新时间
	//  RETURNING cart_item_id, cart_id, product_id, quantity, ischecked, created_at, updated_at
	UpsertItem(ctx context.Context, arg UpsertItemParams) (CartSchemaCartItems, error)
}

var _ Querier = (*Queries)(nil)
